/**
 * This file will be auto-generated by Anchor build.
 * For now, we provide a type placeholder.
 */

import { Idl } from '@coral-xyz/anchor';

export type FortunaProtocol = Idl;

// The actual IDL will be generated in target/idl/fortuna_protocol.json after running `anchor build`
